language: node_js
cache: yarn
node_js:
  - "lts/*"
addons:
  apt:
    update: true
    sources:
    - sourceline: 'deb http://dl.yarnpkg.com/debian/ stable main'
      key_url: 'http://dl.yarnpkg.com/debian/pubkey.gpg'
    packages:
    - yarn
    - ffmpeg
    - shellcheck
  homebrew:
    update: true
    packages:
    - yarn
    - ffmpeg
    - shellcheck
matrix:
  include:
    - name: "Linux"
      os: linux
      dist: xenial
      sudo: required
    - name: "macOS"
      os: osx
      osx_image: xcode10.1
before_install: true
install:
  - yarn install
before_script:
  - cp settings/credentials.example.yaml settings/credentials.yaml
  - cp settings/configurations.example.yaml settings/configurations.yaml
script:
  - yarn test
  - shellcheck -x *.sh
after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
