# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: "ubuntu-16.04"
    mac:
      imageName: "macos-10.14"
    windows:
      imageName: "windows-2019"
  maxParallel: 3

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    yarn install
  displayName: 'Install dependencies'
- script: |
    cp settings/credentials.example.yaml settings/credentials.yaml
    cp settings/configurations.example.yaml settings/configurations.yaml
  displayName: 'Generate settings files'
- script: |
    yarn test
  displayName: 'Test'